import { serve } from 'https://deno.land/std@0.177.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const SUPABASE_URL = Deno.env.get('SUPABASE_URL') ?? '';
const SUPABASE_SERVICE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? '';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  try {
    const { deliveryId } = await req.json();
    if (!deliveryId) {
      return new Response(JSON.stringify({ error: 'deliveryId is required' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY);

    // Fetch delivery + items
    const { data: delivery, error: delErr } = await supabase
      .from('deliveries')
      .select(`*, vendor:profiles!deliveries_vendor_id_fkey(full_name, email)`)
      .eq('id', deliveryId)
      .maybeSingle();

    if (delErr || !delivery) {
      return new Response(JSON.stringify({ error: 'Delivery not found' }), {
        status: 404,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const { data: items } = await supabase
      .from('delivery_location_items')
      .select('*')
      .eq('delivery_id', deliveryId)
      .order('route_number');

    const locationItems = items ?? [];

    // Build PDF as HTML-based content, then generate a simple JSON summary
    // The PDF URL is generated by uploading a text placeholder representing the waybill
    // In production this would use a PDF library like pdfkit
    const totalIssued = locationItems.reduce((s: number, i: { issued_quantity: number }) => s + i.issued_quantity, 0);
    const totalReceived = locationItems.reduce((s: number, i: { received_quantity: number }) => s + i.received_quantity, 0);
    const completedCount = locationItems.filter((i: { status: string }) => i.status === 'completed').length;
    const noIssueCount = locationItems.filter((i: { no_issue_needed: boolean }) => i.no_issue_needed).length;

    // Generate HTML content for the PDF
    const deliveryDateFormatted = delivery.delivery_date;
    const vendorName = delivery.vendor_full_name || delivery.vendor?.full_name || 'Unknown';
    const reportId = deliveryId.slice(0, 8).toUpperCase();
    const generatedDate = new Date().toISOString().split('T')[0];

    const tableRows = locationItems.map((item: {
      route_number: string;
      building_number: string;
      office_name: string;
      sup_number: string;
      estimated_bottles: number;
      issued_quantity: number;
      received_quantity: number;
      officer_name: string | null;
      status: string;
      notes: string | null;
      no_issue_needed: boolean;
    }) => `
      <tr style="border-bottom:1px solid #e5e7eb">
        <td style="padding:6px 8px;font-size:11px">${item.route_number}</td>
        <td style="padding:6px 8px;font-size:11px">${item.building_number}</td>
        <td style="padding:6px 8px;font-size:11px">${item.office_name}</td>
        <td style="padding:6px 8px;font-size:11px">${item.sup_number}</td>
        <td style="padding:6px 8px;font-size:11px;text-align:center">${item.estimated_bottles}</td>
        <td style="padding:6px 8px;font-size:11px;text-align:center">${item.issued_quantity}</td>
        <td style="padding:6px 8px;font-size:11px;text-align:center">${item.received_quantity}</td>
        <td style="padding:6px 8px;font-size:11px">${item.officer_name || (item.no_issue_needed ? 'No Issue Required' : '—')}</td>
        <td style="padding:6px 8px;font-size:11px">${item.no_issue_needed ? 'No Issue' : item.status}</td>
        <td style="padding:6px 8px;font-size:11px">${item.notes || '—'}</td>
      </tr>
    `).join('');

    const htmlContent = `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>Water Bottles Delivery Waybill</title></head>
<body style="font-family:Arial,sans-serif;margin:0;padding:24px;color:#111827">
  <div style="text-align:center;border-bottom:3px solid #2563EB;padding-bottom:16px;margin-bottom:20px">
    <h1 style="font-size:22px;font-weight:800;color:#2563EB;margin:0;letter-spacing:1px">WATER BOTTLES DELIVERY WAYBILL</h1>
    <p style="margin:6px 0 0;color:#6b7280;font-size:12px">Report ID: ${reportId} &nbsp;|&nbsp; Generated: ${generatedDate}</p>
  </div>

  <div style="display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-bottom:20px">
    <div style="border:1px solid #e5e7eb;border-radius:6px;padding:12px">
      <p style="margin:0 0 4px;font-size:11px;color:#6b7280;text-transform:uppercase;font-weight:600">Delivery Date</p>
      <p style="margin:0;font-weight:700;font-size:14px">${deliveryDateFormatted}</p>
    </div>
    <div style="border:1px solid #e5e7eb;border-radius:6px;padding:12px">
      <p style="margin:0 0 4px;font-size:11px;color:#6b7280;text-transform:uppercase;font-weight:600">Vendor Name</p>
      <p style="margin:0;font-weight:700;font-size:14px">${vendorName}</p>
    </div>
    <div style="border:1px solid #e5e7eb;border-radius:6px;padding:12px">
      <p style="margin:0 0 4px;font-size:11px;color:#6b7280;text-transform:uppercase;font-weight:600">Status</p>
      <p style="margin:0;font-weight:700;font-size:14px;color:#16a34a">${delivery.status.toUpperCase()}</p>
    </div>
    <div style="border:1px solid #e5e7eb;border-radius:6px;padding:12px">
      <p style="margin:0 0 4px;font-size:11px;color:#6b7280;text-transform:uppercase;font-weight:600">Report ID</p>
      <p style="margin:0;font-weight:700;font-size:14px">${reportId}</p>
    </div>
  </div>

  <div style="background:#f0f9ff;border:1px solid #bae6fd;border-radius:6px;padding:12px;margin-bottom:20px">
    <h3 style="margin:0 0 10px;font-size:13px;color:#0369a1;text-transform:uppercase;font-weight:700">Summary</h3>
    <div style="display:grid;grid-template-columns:repeat(5,1fr);gap:8px;text-align:center">
      <div><p style="margin:0;font-size:18px;font-weight:800;color:#2563EB">${locationItems.length}</p><p style="margin:0;font-size:10px;color:#6b7280">Total Locations</p></div>
      <div><p style="margin:0;font-size:18px;font-weight:800;color:#16a34a">${completedCount}</p><p style="margin:0;font-size:10px;color:#6b7280">Completed</p></div>
      <div><p style="margin:0;font-size:18px;font-weight:800;color:#6b7280">${noIssueCount}</p><p style="margin:0;font-size:10px;color:#6b7280">No Issue</p></div>
      <div><p style="margin:0;font-size:18px;font-weight:800;color:#2563EB">${totalIssued}</p><p style="margin:0;font-size:10px;color:#6b7280">Total Issued</p></div>
      <div><p style="margin:0;font-size:18px;font-weight:800;color:#16a34a">${totalReceived}</p><p style="margin:0;font-size:10px;color:#6b7280">Total Received</p></div>
    </div>
  </div>

  <h3 style="font-size:13px;margin-bottom:8px;color:#374151;text-transform:uppercase;font-weight:700">Delivery Details</h3>
  <table style="width:100%;border-collapse:collapse;border:1px solid #e5e7eb;font-size:11px">
    <thead>
      <tr style="background:#2563EB;color:white">
        <th style="padding:8px;text-align:left">Route</th>
        <th style="padding:8px;text-align:left">Building</th>
        <th style="padding:8px;text-align:left">Office</th>
        <th style="padding:8px;text-align:left">SUP No.</th>
        <th style="padding:8px;text-align:center">Est.</th>
        <th style="padding:8px;text-align:center">Issued</th>
        <th style="padding:8px;text-align:center">Received</th>
        <th style="padding:8px;text-align:left">Officer</th>
        <th style="padding:8px;text-align:left">Status</th>
        <th style="padding:8px;text-align:left">Notes</th>
      </tr>
    </thead>
    <tbody>${tableRows}</tbody>
    <tfoot>
      <tr style="background:#f3f4f6;font-weight:700">
        <td colspan="5" style="padding:8px;font-size:11px">TOTALS</td>
        <td style="padding:8px;text-align:center;font-size:12px">${totalIssued}</td>
        <td style="padding:8px;text-align:center;font-size:12px">${totalReceived}</td>
        <td colspan="3"></td>
      </tr>
    </tfoot>
  </table>

  <div style="margin-top:32px;border-top:2px solid #e5e7eb;padding-top:20px">
    <h3 style="font-size:13px;margin-bottom:16px;color:#374151;text-transform:uppercase;font-weight:700">Signatures</h3>
    <div style="display:grid;grid-template-columns:1fr 1fr;gap:24px">
      <div style="border:1px solid #e5e7eb;border-radius:6px;padding:16px">
        <p style="margin:0 0 4px;font-size:11px;color:#6b7280;font-weight:600">VENDOR NAME</p>
        <p style="margin:0 0 12px;font-weight:700">${delivery.vendor_full_name || '—'}</p>
        ${delivery.vendor_signature_url
          ? `<img src="${delivery.vendor_signature_url}" style="max-height:60px;border:1px solid #e5e7eb;border-radius:4px;padding:4px;background:white" alt="Vendor Signature"/>`
          : '<div style="height:60px;border:1px dashed #d1d5db;border-radius:4px;display:flex;align-items:center;justify-content:center;color:#9ca3af;font-size:11px">No signature</div>'
        }
        <p style="margin:8px 0 0;font-size:10px;color:#6b7280">Delivery Date: ${deliveryDateFormatted}</p>
      </div>
      <div style="border:1px solid #e5e7eb;border-radius:6px;padding:16px">
        <p style="margin:0 0 4px;font-size:11px;color:#6b7280;font-weight:600">ADMIN NAME</p>
        <p style="margin:0 0 12px;font-weight:700">${delivery.admin_full_name || '—'}</p>
        ${delivery.admin_signature_url
          ? `<img src="${delivery.admin_signature_url}" style="max-height:60px;border:1px solid #e5e7eb;border-radius:4px;padding:4px;background:white" alt="Admin Signature"/>`
          : '<div style="height:60px;border:1px dashed #d1d5db;border-radius:4px;display:flex;align-items:center;justify-content:center;color:#9ca3af;font-size:11px">No signature</div>'
        }
        <p style="margin:8px 0 0;font-size:10px;color:#6b7280">Approved: ${delivery.approved_at ? delivery.approved_at.split('T')[0] : '—'}</p>
      </div>
    </div>
  </div>
</body>
</html>`;

    // Upload HTML as PDF placeholder to Supabase Storage
    const sanitizedVendor = vendorName.replace(/[^a-zA-Z0-9]/g, '_').slice(0, 30);
    const filename = `Water_Bottles_Delivery_Waybill_${deliveryDateFormatted}_${sanitizedVendor}.html`;
    const storagePath = `pdfs/${deliveryId}/${filename}`;

    const htmlBytes = new TextEncoder().encode(htmlContent);
    const { data: uploadData, error: uploadErr } = await supabase.storage
      .from('pdfs')
      .upload(storagePath, htmlBytes, { contentType: 'text/html', upsert: true });

    if (uploadErr) {
      console.error('Upload error:', uploadErr);
      return new Response(JSON.stringify({ error: 'Failed to upload PDF' }), {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const { data: urlData } = supabase.storage.from('pdfs').getPublicUrl(storagePath);
    const pdfUrl = urlData.publicUrl;

    // Update delivery with PDF URL
    await supabase.from('deliveries').update({ final_signed_pdf_url: pdfUrl }).eq('id', deliveryId);

    // Log to audit
    await supabase.from('audit_logs').insert({
      action: 'pdf_generated',
      entity_type: 'delivery',
      entity_id: deliveryId,
      details: { pdf_url: pdfUrl },
    });

    return new Response(JSON.stringify({ success: true, pdfUrl }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  } catch (err) {
    console.error('generate-pdf error:', err);
    return new Response(JSON.stringify({ error: String(err) }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
